Implement Fuzzy matching for Calorie Search
loseitIRC/loseitbot pull request #10
Opened 2017-09-08 13:42 UTC by NeilHanlon

Right now we just take the first result, which appears to just be some random sort the database is doing. This method appears to be really good at finding much better matches.

https://gist.github.com/NeilHanlon/9e4cc26215ab19cf2c080721b12679fd

Will need to install fuzzywuzzy[speedup] in the virtualenv

2017-09-08 16:59 UTC, SnoopJeDi commented on modules/nutrients/__init__.py
> +      foodname = topfood['name']
`topfood` should be `topFood`

2017-09-08 17:00 UTC, SnoopJeDi commented on modules/nutrients/__init__.py
> +    if 'list' in results.keys():
Fails if the query fails because it returns `False` but that's an easy fix, we can make it return `{}` instead. So this is fine.

2017-09-08 17:03 UTC, SnoopJ requested changes
Indents should be 4 spaces to fit existing style

Results don't seem to get sorted quite the way we'd want, as-is. An example exchange:

    < SnoopJeDi> !calories chicken
    < terribot> SnoopJeDi: "Fat, chicken" has 900 kcal per 100 g. See more results at                  https://ndb.nal.usda.gov/ndb/search/list?qlookup=chicken

The corresponding `weighted` for this example:

```python
weighted=[('Fat, chicken', 78), ('Chicken spread', 67), ('Chicken, meatless', 61), ('Gravy, chicken, dry', 58), ('Chicken, ground, raw', 56)]
```

Not really sure how we want to address that, maybe we need to make the matcher aware of the semantic content of commas in the USDA names (i.e. _"Fat, chicken"_ is fat foremost which comes from chicken, but _"Chicken, ground"_ is chicken foremost)

2017-09-29 18:12 UTC, NeilHanlon commented
I am going to close this PR and open a new one on a different branch. because not branching before I made the PR is really messing up my git

2017-09-29 18:12 UTC, closed without merging